const guidelines = {
  Alabama: "http://www.adph.org/",
  Alaska: "http://dhss.alaska.gov/Pages/default.aspx",
  "American Samoa": "http://dhss.as/",
  Arizona: "http://www.azdhs.gov/",
  Arkansas: "https://www.healthy.arkansas.gov/",
  California: "https://www.cdph.ca.gov/",
  Colorado: "https://www.colorado.gov/cdphe",
  Connecticut: "http://www.ct.gov/dph/site/default.asp",
  Delaware: "http://www.dhss.delaware.gov/dhss/dph/index.html",
  "District of Columbia": "http://doh.dc.gov/",
  Florida: "http://www.floridahealth.gov/",
  Georgia: "http://dph.georgia.gov/",
  Guam: "https://dphss.guam.gov/dph/",
  Hawaii: "http://health.hawaii.gov/",
  Idaho: "http://www.healthandwelfare.idaho.gov/",
  Illinois: "http://www.idph.state.il.us/",
  Indiana: "http://www.in.gov/isdh/",
  Iowa: "http://idph.iowa.gov/",
  Kansas: "http://www.kdheks.gov/",
  Kentucky: "https://chfs.ky.gov/agencies/dph/Pages/default.aspx",
  Louisiana: "http://dhh.louisiana.gov/",
  Maine: "http://www.maine.gov/dhhs/index.shtml",
  "Marshall Islands": "None",
  Maryland: "http://dhmh.maryland.gov/Pages/Index.aspx",
  Massachusetts: "https://www.mass.gov/orgs/department-of-public-health",
  Michigan: "http://www.michigan.gov/mdch",
  Micronesia: "http://www.fsmgov.org/ngovt.html",
  Minnesota: "http://www.health.state.mn.us/",
  Mississippi: "http://www.msdh.state.ms.us/",
  Missouri: "http://health.mo.gov/index.php",
  Montana: "http://dphhs.mt.gov/",
  Nebraska: "http://dhhs.ne.gov/Pages/default.aspx",
  Nevada: "http://dpbh.nv.gov/",
  "New Hampshire": "http://www.dhhs.nh.gov/",
  "New Jersey": "http://www.state.nj.us/health/",
  "New Mexico": "http://nmhealth.org/",
  "New York": "https://www.health.ny.gov/",
  "North Carolina": "http://www.ncdhhs.gov/",
  "North Dakota": "http://www.ndhealth.gov/",
  "Northern Marianas": "http://chcc.gov.mp/",
  Ohio: "https://www.odh.ohio.gov/",
  Oklahoma: "https://www.ok.gov/health/",
  Oregon: "http://www.oregon.gov/oha/ph/pages/index.aspx",
  Palau: "http://www.palauhealth.org/",
  Pennsylvania: "https://www.health.pa.gov/Pages/default.aspx",
  "Puerto Rico": "http://www.salud.gov.pr/Pages/Home.aspx",
  "Rhode Island": "http://www.health.state.ri.us/",
  "South Carolina": "http://www.scdhec.gov/",
  "South Dakota": "http://doh.sd.gov/",
  Tennessee: "https://www.tn.gov/health.html",
  Texas: "https://www.dshs.state.tx.us/",
  Utah: "https://health.utah.gov/",
  Vermont: "http://healthvermont.gov/",
  "Virgin Islands": "https://doh.vi.gov/",
  Virginia: "http://www.vdh.state.va.us/",
  Washington: "http://www.doh.wa.gov/",
  "West Virginia": "http://www.dhhr.wv.gov/bph/Pages/default.aspx",
  Wisconsin: "https://www.dhs.wisconsin.gov/",
  Wyoming: "http://health.wyo.gov/",
};

export default guidelines;
